apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: room-management
data:
  datasources.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        editable: true

  dashboards.yml: |
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards

  room-management-dashboard.json: |
    {
      "dashboard": {
        "id": null,
        "title": "Room Management System Dashboard",
        "tags": ["room-management", "microservices"],
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "HTTP Requests Total",
            "type": "stat",
            "targets": [
              {
                "expr": "sum(rate(http_requests_total[5m])) by (job)",
                "refId": "A"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "unit": "reqps"
              }
            },
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 0}
          },
          {
            "id": 2,
            "title": "HTTP Request Duration",
            "type": "graph",
            "targets": [
              {
                "expr": "histogram_quantile(0.95, rate(http_request_duration_ms_bucket[5m]))",
                "legendFormat": "95th percentile",
                "refId": "A"
              },
              {
                "expr": "histogram_quantile(0.50, rate(http_request_duration_ms_bucket[5m]))",
                "legendFormat": "50th percentile",
                "refId": "B"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "unit": "ms"
              }
            },
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 0}
          },
          {
            "id": 3,
            "title": "Service Status",
            "type": "stat",
            "targets": [
              {
                "expr": "up{job=~\".*service.*\"}",
                "refId": "A"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "mappings": [
                  {
                    "options": {
                      "0": {"text": "DOWN", "color": "red"},
                      "1": {"text": "UP", "color": "green"}
                    },
                    "type": "value"
                  }
                ]
              }
            },
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 8}
          },
          {
            "id": 4,
            "title": "Rooms Created",
            "type": "stat",
            "targets": [
              {
                "expr": "rooms_created_total",
                "refId": "A"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "unit": "short"
              }
            },
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 8}
          },
          {
            "id": 5,
            "title": "Memory Usage",
            "type": "graph",
            "targets": [
              {
                "expr": "process_working_set_bytes",
                "legendFormat": "{{job}}",
                "refId": "A"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "unit": "bytes"
              }
            },
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 16}
          },
          {
            "id": 6,
            "title": "CPU Usage",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(process_cpu_seconds_total[5m])",
                "legendFormat": "{{job}}",
                "refId": "A"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "unit": "percent"
              }
            },
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 16}
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "refresh": "10s"
      }
    }